# ============================================================
# launch_agents_2.ps1
#
# Launch Claude sessions 16 -> 32
#
# Repo structure:
#
# aichessathon-starter/
#   my-agents-readmes/    <- README specifications
#   agents/               <- implementations generated by Claude
#   .claude_prompts/      <- generated prompts
#   .claude_launchers/    <- generated launcher scripts
#   .venv/                <- project Python environment
#
# ============================================================


# ------------------------------------------------------------
# Project paths
# ------------------------------------------------------------

$Root = "E:\sourcecode\ai-chess-original\aichessathon-starter"

$ReadmeDir  = Join-Path $Root "my-agents-readmes"
$AgentsDir  = Join-Path $Root "agents"

$PromptsDir = Join-Path $Root ".claude_prompts"
$LaunchDir  = Join-Path $Root ".claude_launchers"

$PythonExe = Join-Path $Root ".venv\Scripts\python.exe"


# ------------------------------------------------------------
# Create required directories
# ------------------------------------------------------------

New-Item -ItemType Directory -Force -Path $AgentsDir  | Out-Null
New-Item -ItemType Directory -Force -Path $PromptsDir | Out-Null
New-Item -ItemType Directory -Force -Path $LaunchDir  | Out-Null


# ------------------------------------------------------------
# Claude sessions
# ------------------------------------------------------------

$Bots = @(

    @{
        Id = 16
        Readme = "16_MASTER_README.md"
        Folder = "16_master"
        Role = "integration manager"
    },

    @{
        Id = 17
        Readme = "17_RULE_BASED_ENGINE.md"
        Folder = "17_rule_based"
        Role = "rule-based engine"
    },

    @{
        Id = 18
        Readme = "18_MINIMAX_NEGAMAX_ALPHA_BETA.md"
        Folder = "18_alpha_beta"
        Role = "minimax negamax alpha-beta engine"
    },

    @{
        Id = 19
        Readme = "19_HANDCRAFTED_EVALUATION.md"
        Folder = "19_handcrafted_eval"
        Role = "handcrafted evaluation engine"
    },

    @{
        Id = 20
        Readme = "20_PVS_SELECTIVE_SEARCH.md"
        Folder = "20_pvs"
        Role = "PVS selective-search engine"
    },

    @{
        Id = 21
        Readme = "21_NNUE_STOCKFISH_DISTILLATION.md"
        Folder = "21_nnue"
        Role = "self-trained NNUE engine"
    },

    @{
        Id = 22
        Readme = "22_SUPERVISED_POLICY_NETWORK.md"
        Folder = "22_policy"
        Role = "supervised policy-network engine"
    },

    @{
        Id = 23
        Readme = "23_POLICY_VALUE_ALPHA_BETA_HYBRID.md"
        Folder = "23_hybrid"
        Role = "policy value alpha-beta hybrid"
    },

    @{
        Id = 24
        Readme = "24_ALPHAZERO_SELF_PLAY.md"
        Folder = "24_alphazero"
        Role = "AlphaZero-style self-play engine"
    },

    @{
        Id = 25
        Readme = "25_POLICY_VALUE_PUCT_MCTS.md"
        Folder = "25_puct"
        Role = "policy value PUCT MCTS engine"
    },

    @{
        Id = 26
        Readme = "26_MUZERO.md"
        Folder = "26_muzero"
        Role = "MuZero engine"
    },

    @{
        Id = 27
        Readme = "27_CHESSFORMER.md"
        Folder = "27_chessformer"
        Role = "Chessformer engine"
    },

    @{
        Id = 28
        Readme = "28_SEARCHLESS_TRANSFORMER_CHESSBENCH.md"
        Folder = "28_chessbench"
        Role = "searchless ChessBench transformer engine"
    },

    @{
        Id = 29
        Readme = "29_DEEPCHESS_PAIRWISE.md"
        Folder = "29_deepchess"
        Role = "DeepChess pairwise engine"
    },

    @{
        Id = 30
        Readme = "30_GIRAFFE_DEEP_RL.md"
        Folder = "30_giraffe"
        Role = "Giraffe deep-RL learned evaluation engine"
    },

    @{
        Id = 31
        Readme = "31_TDLEAF_KNIGHTCAP.md"
        Folder = "31_tdleaf"
        Role = "TDLeaf KnightCap engine"
    },

    @{
        Id = 32
        Readme = "32_AUXILIARY_BOOKS_TABLEBASES.md"
        Folder = "32_auxiliary"
        Role = "opening book and tablebase experiment"
    }

)


# ------------------------------------------------------------
# Validate environment
# ------------------------------------------------------------

Write-Host ""
Write-Host "==============================================" -ForegroundColor Cyan
Write-Host " AI CHESSATHON CLAUDE MULTI-AGENT LAUNCHER" -ForegroundColor Cyan
Write-Host "==============================================" -ForegroundColor Cyan
Write-Host ""

Write-Host "Project root:    $Root"
Write-Host "READMEs:         $ReadmeDir"
Write-Host "Agents:          $AgentsDir"
Write-Host "Python:          $PythonExe"
Write-Host ""


if (-not (Test-Path $Root)) {

    Write-Host "ERROR: Project root does not exist:" -ForegroundColor Red
    Write-Host $Root

    exit 1
}


if (-not (Test-Path $ReadmeDir)) {

    Write-Host "ERROR: README directory does not exist:" -ForegroundColor Red
    Write-Host $ReadmeDir

    exit 1
}


if (-not (Test-Path $PythonExe)) {

    Write-Host "ERROR: Project virtual environment Python not found:" -ForegroundColor Red
    Write-Host $PythonExe

    exit 1
}


if (-not (Get-Command claude -ErrorAction SilentlyContinue)) {

    Write-Host "ERROR: Claude CLI not found." -ForegroundColor Red
    Write-Host ""
    Write-Host "Test it manually with:"
    Write-Host ""
    Write-Host "    claude"
    Write-Host ""

    exit 1
}


if (-not (Get-Command wt.exe -ErrorAction SilentlyContinue)) {

    Write-Host "ERROR: Windows Terminal wt.exe not found." -ForegroundColor Red

    exit 1
}


# ------------------------------------------------------------
# Launch each independent Claude session
# ------------------------------------------------------------

foreach ($Bot in $Bots) {

    $Id = $Bot.Id

    $ReadmePath = Join-Path $ReadmeDir $Bot.Readme
    $AgentDir   = Join-Path $AgentsDir $Bot.Folder

    $PromptFile = Join-Path $PromptsDir "$Id.txt"
    $Launcher   = Join-Path $LaunchDir "$Id.ps1"


    # --------------------------------------------------------
    # Check README exists
    # --------------------------------------------------------

    if (-not (Test-Path $ReadmePath)) {

        Write-Host ""
        Write-Host "SKIPPING SESSION $Id" -ForegroundColor Yellow
        Write-Host "Missing README:"
        Write-Host $ReadmePath

        continue
    }


    # --------------------------------------------------------
    # Create isolated implementation directory
    # --------------------------------------------------------

    New-Item `
        -ItemType Directory `
        -Force `
        -Path $AgentDir `
        | Out-Null


    # --------------------------------------------------------
    # Claude prompt
    # --------------------------------------------------------

    $Prompt = @"

You are Claude session $Id.

You are an independent AI Chessathon research and engineering agent.

============================================================
YOUR ASSIGNMENT
============================================================

ARCHITECTURE:

$($Bot.Role)


ARCHITECTURE README:

$ReadmePath


YOUR IMPLEMENTATION DIRECTORY:

$AgentDir


PROJECT ROOT:

$Root


PROJECT PYTHON:

$PythonExe


============================================================
IMPORTANT FILESYSTEM RULE
============================================================

You share this repository with MANY OTHER Claude sessions.

Other agents are working concurrently.

ALL architecture-specific implementation work MUST stay inside:

$AgentDir

Do NOT modify:

$AgentsDir\<another-agent-folder>

Do NOT overwrite another Claude session's files.

You MAY inspect:

$Root\harness
$Root\baselines
$Root\docs
$Root\agent.py
$Root\README.md
$Root\pyproject.toml
$Root\AGENTS.md
$Root\CLAUDE.md

to understand the competition and harness.

Do not casually modify shared repository files.


============================================================
FIRST TASK
============================================================

Before writing code:

1. Read the ENTIRE file:

$ReadmePath

2. Inspect:

$Root\harness
$Root\baselines
$Root\agent.py
$Root\README.md
$Root\pyproject.toml

3. Understand how the Chessathon harness calls agents.

4. Understand how arena games are launched.

5. Understand how FEN and time_left_ms are passed.

6. Then create a short implementation plan in:

$AgentDir\IMPLEMENTATION.md

7. Immediately begin implementing.

DO NOT stop after making the plan.


============================================================
REQUIRED FINAL INTERFACE
============================================================

Your working agent MUST ultimately expose:

def get_move(fen: str, time_left_ms: int) -> str:

It must return exactly one LEGAL chess move in UCI notation.

Examples:

e2e4
g1f3
e7e8q


============================================================
COMPETITION TARGET
============================================================

Optimize for:

1 CPU core
2 GB RAM
No GPU
No internet at tournament runtime
Python 3.12
50 MB maximum submission size UNCOMPRESSED
90 second initialization budget
120 seconds initial game clock
+0.5 seconds increment per move


============================================================
PYTHON ENVIRONMENT
============================================================

Use THIS Python interpreter:

$PythonExe

Do NOT accidentally use another global environment.

When running commands, prefer:

& "$PythonExe" script.py

or invoke project tools using the existing project environment.


============================================================
COMPETITION LEGALITY
============================================================

You MAY:

- implement algorithms described in academic papers
- independently implement published algorithmic ideas
- train your own neural networks from RANDOM initialization
- use Stockfish OFFLINE as a teacher for training labels if allowed
- create your own datasets
- ship your own trained model weights
- use allowed python-chess functionality

You MUST NOT:

- ship Stockfish
- call Stockfish during tournament runtime
- translate Stockfish source into Python
- port another chess engine
- copy another engine's implementation
- ship Stockfish NNUE weights
- ship Lc0 weights
- ship Maia weights
- submit a fine-tuned published chess network
- disguise another engine as a lookup table

Any neural model shipped must be trained by this project.


============================================================
BUILD PROCEDURE
============================================================

Work incrementally.

PHASE 1
-------
Create the smallest possible working implementation.

Verify:

- import succeeds
- get_move() runs
- returned move is legal
- no crash


PHASE 2
-------
Implement the actual architecture in your README.

Do NOT silently replace it with another architecture.


PHASE 3
-------
Create correctness tests.


PHASE 4
-------
Optimize runtime.


PHASE 5
-------
Benchmark using the provided Chessathon harness.


PHASE 6
-------
Find weaknesses.

Fix them.

Benchmark again.


============================================================
MANDATORY CHESS TESTS
============================================================

Test:

- normal move
- captures
- check
- check evasion
- checkmate
- stalemate
- kingside castling
- queenside castling
- en passant
- queen promotion
- rook promotion
- bishop promotion
- knight promotion

Use python-chess as the legal-move authority where appropriate.


============================================================
CLOCK TESTS
============================================================

Test at least:

time_left_ms = 50
time_left_ms = 100
time_left_ms = 500
time_left_ms = 1000
time_left_ms = 5000
time_left_ms = 30000
time_left_ms = 120000

Always establish a legal fallback move BEFORE expensive work begins.

Never lose a game because the algorithm returned nothing after timing out.


============================================================
BENCHMARKING
============================================================

Use the existing harness and arena.

Play against available baselines.

Prefer paired games:

Game A:
your agent White

Game B:
your agent Black

using the same starting position where possible.


Record:

wins
draws
losses
score percentage
illegal moves
crashes
timeouts
average move time


For search agents additionally record:

nodes
nodes/sec
search depth
selective depth
TT hits
qnodes


For ML agents additionally record:

model parameters
model file size
batch-1 inference latency
training loss
validation metrics
CPU inference speed


============================================================
OUTPUT FILES
============================================================

Create at minimum:

$AgentDir\agent.py

$AgentDir\README.md

$AgentDir\IMPLEMENTATION.md

$AgentDir\RESULTS.md


If ML training is used, also create:

$AgentDir\training\

$AgentDir\models\

$AgentDir\tests\


============================================================
AUTONOMOUS DEBUGGING
============================================================

Do NOT stop just because an error occurs.

If a command fails:

1. read the traceback
2. reproduce the failure
3. determine root cause
4. fix it
5. rerun the failing test
6. rerun regression tests
7. continue development


Do not repeatedly ask the user questions that can be answered by:

- reading the README
- reading repository code
- reading the paper
- reading a traceback
- running a test


============================================================
PERFORMANCE PHILOSOPHY
============================================================

The objective is:

HIGHEST CHESS ELO UNDER ACTUAL CONTEST CONDITIONS

NOT:

largest neural network

most complicated algorithm

best training loss

most elegant architecture


A feature only counts as an improvement if it improves actual playing
strength or reliability.


============================================================
IMPORTANT
============================================================

Do not merely describe what code should exist.

ACTUALLY:

- create the files
- write the implementation
- execute it
- run tests
- debug it
- run arena games
- record results
- improve it


============================================================
START NOW
============================================================

FIRST read:

$ReadmePath

THEN inspect the starter repository.

THEN begin implementation inside:

$AgentDir

Continue autonomously.

"@


    # --------------------------------------------------------
    # Save prompt
    # --------------------------------------------------------

    Set-Content `
        -Path $PromptFile `
        -Value $Prompt `
        -Encoding UTF8


    # --------------------------------------------------------
    # Create session-specific launcher
    # --------------------------------------------------------

    $LauncherContent = @"

Set-Location "$Root"

`$Host.UI.RawUI.WindowTitle = "Chess Agent $Id - $($Bot.Role)"

Write-Host ""
Write-Host "=================================================" -ForegroundColor Cyan
Write-Host " CLAUDE CHESS AGENT $Id" -ForegroundColor Cyan
Write-Host " $($Bot.Role)" -ForegroundColor Cyan
Write-Host "=================================================" -ForegroundColor Cyan
Write-Host ""

Write-Host "README:"
Write-Host "$ReadmePath" -ForegroundColor Yellow

Write-Host ""

Write-Host "Implementation:"
Write-Host "$AgentDir" -ForegroundColor Green

Write-Host ""

`$Prompt = Get-Content -Raw "$PromptFile"

claude "`$Prompt"

"@


    Set-Content `
        -Path $Launcher `
        -Value $LauncherContent `
        -Encoding UTF8


    # --------------------------------------------------------
    # Launch Windows Terminal tab
    # --------------------------------------------------------

    $TabTitle = "Chess-$Id-$($Bot.Folder)"


    wt.exe -w 0 new-tab `
        --title "$TabTitle" `
        -d "$Root" `
        powershell.exe `
        -NoExit `
        -ExecutionPolicy Bypass `
        -File "$Launcher"


    Write-Host "Started $Id : $($Bot.Role)" -ForegroundColor Green


    # Avoid launching all Node/Claude processes on exactly the
    # same instant.
    Start-Sleep -Milliseconds 600
}


# ------------------------------------------------------------
# Finished
# ------------------------------------------------------------

Write-Host ""
Write-Host "==============================================" -ForegroundColor Cyan
Write-Host " ALL AVAILABLE CLAUDE AGENTS LAUNCHED" -ForegroundColor Cyan
Write-Host "==============================================" -ForegroundColor Cyan
Write-Host ""

Write-Host "READMEs:"
Write-Host "  $ReadmeDir"
Write-Host ""

Write-Host "Implementations:"
Write-Host "  $AgentsDir"
Write-Host ""

Write-Host "Prompts:"
Write-Host "  $PromptsDir"
Write-Host ""

Write-Host "Session launchers:"
Write-Host "  $LaunchDir"
Write-Host ""