"""Quantise a trained checkpoint to int16 and write weights/nnue.safetensors + provenance.

    python training/export.py --ckpt models/nnue.pt --out weights/nnue.safetensors
"""

from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import os
import subprocess
import sys

import numpy as np
import torch

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)
from nnue import NUM_FEATURES, QA, QB, SCALE, write_safetensors  # noqa: E402


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ckpt", default=os.path.join(ROOT, "models", "nnue.pt"))
    parser.add_argument("--out", default=os.path.join(ROOT, "weights", "nnue.safetensors"))
    args = parser.parse_args()
    ck = torch.load(args.ckpt, map_location="cpu", weights_only=False)
    state = ck["state"]
    hidden = ck["hidden"]
    ft = state["ft.weight"][:NUM_FEATURES].numpy()
    ft_bias = state["ft_bias"].numpy()
    out_w = state["out.weight"].numpy().reshape(-1)
    out_b = float(state["out.bias"].numpy()[0])

    W1 = np.round(ft * QA).astype(np.int16)
    B1 = np.round(ft_bias * QA).astype(np.int16)
    W2 = np.round(out_w * QB).astype(np.int16)
    B2 = np.array([round(out_b * QA * QB)], dtype=np.int32)
    # worst-case accumulator magnitude: 32 largest |weights| per hidden unit + bias
    worst = np.sort(np.abs(W1.astype(np.int64)), axis=0)[-32:].sum(0) + np.abs(B1.astype(np.int64))
    print(f"hidden {hidden}; |W1| max {np.abs(W1).max()}, worst-case accumulator {worst.max()} (int16 limit 32767)")
    assert worst.max() < 32767, "accumulator could overflow int16"
    assert np.abs(out_w * QB).max() < 32767

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    meta = {
        "arch": f"(768->{hidden})x2->1 crelu",
        "QA": str(QA),
        "QB": str(QB),
        "SCALE": str(SCALE),
        "trained_by": "aichessathon-starter agents/21_nnue training/train.py from random init",
        "positions": str(ck.get("positions")),
        "train_args": json.dumps(ck.get("args", {})),
    }
    write_safetensors(args.out, {"W1": W1, "B1": B1, "W2": W2, "B2": B2}, meta)
    size = os.path.getsize(args.out)
    sha = hashlib.sha256(open(args.out, "rb").read()).hexdigest()
    try:
        commit = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
    except Exception:
        commit = "unknown"
    prov = os.path.join(ROOT, "models", "PROVENANCE.md")
    hist = ck.get("history", [])
    last = hist[-1] if hist else {}
    with open(prov, "a", encoding="utf-8") as f:
        f.write(
            f"\n## {os.path.basename(args.out)} exported {datetime.datetime.now().isoformat(timespec='seconds')}\n\n"
            f"- checkpoint: `{os.path.relpath(args.ckpt, ROOT)}` (hidden {hidden}, {ck.get('positions')} positions)\n"
            f"- training args: `{json.dumps(ck.get('args', {}))}`\n"
            f"- final epoch: `{json.dumps(last)}`\n"
            f"- teacher: Stockfish 17.1 official binary, offline, fixed node limit (training/datagen.py)\n"
            f"- dataset: self-play from random openings generated by training/datagen.py\n"
            f"- initialisation: random (torch.manual_seed({ck.get('args', {}).get('seed')}))\n"
            f"- git commit: {commit}\n"
            f"- file: {size} bytes, sha256 {sha}\n"
        )
    print(f"wrote {args.out} ({size} bytes); provenance appended to {prov}")


if __name__ == "__main__":
    main()
